/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Crash Team Racing Recomp)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* confirmed: Mode/dispatch leaf jal'd from NdIntroMeshDraw (link 0x80044580). gp+0x4D4 mode + gp+0x4D8 depth countdown → NdIntroOtBase / Mode1 / NdIntroOtFar. v0 → $fp for all PolyG4 AddPrims. Probe nd_intro=2 @ ND digits: 100% NdIntroOtFar (44154/44268=0); $fp=0x800FBD40 ≈ ot_base+0x1005. */
#define PSX_FN_NdIntroDrawDispatch 0x800440A0u
#define func_800440A0 NdIntroDrawDispatch  /* alias */

/* guessed: Returns *(game+buf*4+0x18C8) OT base. game=*(0x8008D2AC), buf=game+0xC. Unused during ND digit window (count=0). */
#define PSX_FN_NdIntroOtBase 0x80044154u
#define func_80044154 NdIntroOtBase  /* alias */

/* confirmed: jr $ra with v0=*(game+0x25C)+0xFFC → ot_index 0x1005. Depth≤0 path (mode==0). Reverse-OT high→low: PolyG4 rank 0. Digits use ot_base+4/+16 (index 1/4) → nearest (rank~4829). Wood OTZ~0xB00..0x1007 sits with OtFar — digits overpaint by guest OT design. */
#define PSX_FN_NdIntroOtFar 0x800441A8u
#define func_800441A8 NdIntroOtFar  /* alias */

/* guessed: Same OT-base load as NdIntroOtBase; mode==1 / mode2 fallthroughs. Unused during ND digit window (count=0). */
#define PSX_FN_NdIntroOtBaseMode1 0x80044268u
#define func_80044268 NdIntroOtBaseMode1  /* alias */

/* guessed: ND crate intro draw (2572B). RTPT→scratch→clip→PolyG4(0x38) only (code 56 @0x80044E04). GTE ra 0x80044580: SX~206..645, obj Vx~-3006..-306, TR=0/H=256. OT via NdIntroOtFar (rank 0). Right-band 0x38s are gray/white gouraud — GP0 has ZERO textured prims with xmax>301 (wood FT3/GT3 stop at 301). Digits 0x3C ot~4829 overpaint this band. */
#define PSX_FN_NdIntroMeshDraw 0x800444ECu
#define func_800444EC NdIntroMeshDraw  /* alias */

/* guessed: ND digit/glow FX (4864B). Probe nd_intro=4 @ ND digits: entry count=0 while DigitGt4 0x80023094 fires — digit quads are built outside this function. Glow site 0x80053E10 also 0. */
#define PSX_FN_NdIntroDigitFx 0x80052F98u
#define func_80052F98 NdIntroDigitFx  /* alias */

/* confirmed: Parent of GTE ras 0x80069C3C/60/84/A8. LIVE during digit-rain look-up (~f1274+): 176 RTPTs/frame, TR=0 via ctc2. Right-flap PolyFT3 via NdIntroSiblingRtptEmit (SX~390..595 FLAG=0). Linked at farthest OT bucket (gpu ot_rank 0) so additive 0x36 glow (~rank 1832) blends over them — looks like a short WoodEmit flap. WoodEmit 0x34 SX≤313 is the inner band only. */
#define PSX_FN_NdIntroMeshSiblingDraw 0x800693C8u
#define func_800693C8 NdIntroMeshSiblingDraw  /* alias */

/* confirmed: Caller 0x80036F50. Loads RT from a1+40..56, ctc2 TR=0, a3=*(a1+244)+4092 (last slot of 1024-entry OT; a1+244 alternates 0x800F5D44/0x800F4D2C). Face loop AddPrim t9=a3+face_hi — look-up right flaps use face_hi≈0 → farthest bucket (gpu ot_rank 0) while additive 0x36 glow ranks ~1832, so glow blends over the flap. WoodEmit AVSZ ranks ~1200–2046. PSX_ND_SIB_OT_LIFT moves a3 (neg toward nearer); -1023 still before glow; -1024 wraps/corrupts OT. */
#define PSX_FN_NdIntroSiblingRtptEmit 0x80069BB0u
#define func_80069BB0 NdIntroSiblingRtptEmit  /* alias */

/* confirmed: Live textured wood (396B). RTPT ra 0x8006A564 + RTPS ra 0x8006A69C. Digit-rain look-up: WoodEmit 0x34 SX≤~313 (TR≈(0,948,1992)/H=320) — this is only the inner band. Right-flap extent past ~313 is NdIntroSiblingRtptEmit PolyFT3(0x30) SX~390..595, not missing WoodEmit verts. Later rain SX grows as TR.z falls. MENU ~f3100 SX≤301 false-positive. */
#define PSX_FN_NdIntroWoodEmit 0x8006A52Cu
#define func_8006A52C NdIntroWoodEmit  /* alias */

/* guessed: 996B near-duplicate of NdIntroWoodEmit. Only reached via not-taken of bgez $zero @ 0x8006A6B0 — dead on MIPS. Keep labeled; do not hook. */
#define PSX_FN_NdIntroWoodEmitTwin 0x8006A6B8u
#define func_8006A6B8 NdIntroWoodEmitTwin  /* alias */

/* guessed: jalr $s6 from WoodEmit; model+0xF0. Bitstream/delta decode into scratch — not raw SVECTOR at +C0. */
#define PSX_FN_NdIntroWoodVertLoad 0x8006A8E0u
#define func_8006A8E0 NdIntroWoodVertLoad  /* alias */

/* guessed: ND intro GP0 submit helper — stores DR_ENV-ish words then jr $ra; digit+mesh packets stamp store PC 0x800748B4 */
#define PSX_FN_GpuPacketLinkTail 0x80074870u
#define func_80074870 GpuPacketLinkTail  /* alias */

/* guessed: Sibling of GpuPacketLinkTail; ORs 0x10000000 into packet word (semi/code bit helper) */
#define PSX_FN_GpuPacketOrCode 0x800748B8u
#define func_800748B8 GpuPacketOrCode  /* alias */

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8007793Cu
#define func_8007793C BootEntry  /* alias */
