/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Crash Team Racing)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8007793Cu
#define func_8007793C BootEntry  /* alias */
